### ISSUE TITLE
Concurrency option as optional

### ISSUE THREAD

**Issue by grandmarnier** [uken/guard-sidekiq#11]
At v0.1.0, concurrency option is provided from cmd even if guardfile not specifies and overrides config file.
It would be more clear to run concurreny option when guardfile states it.

**Comment by pitr** [comment]
Could you elaborate? Is that a guard config I am not aware of?

**Comment by grandmarnier** [comment]
In  /lib/guard/sidekiq.rb
```ruby
def cmd
    ...
    command << "--timeout #{@options[:timeout]}"          if @options[:timeout]
    command << "--require #{@options[:require]}"          if @options[:require]
    command << "--concurrency #{@options[:concurrency]}" # <-- here

    command.join(' ')
end
```
concurrency option is not guarded, and options[:concurrency] defaults to 1.

**Comment by pitr** [comment]
ah, good catch! Seems like a relatively easy thing, would you be able to provide a PR for this?

**Comment by grandmarnier** [comment]
Ok, I will request PR. Thank you for review.
